---
title: "Group Project_Data _Processing"
author: "EMMA OO"
date: '2022-06-12'
output: html_document
---

```{r}
library(caret)
library(dplyr)
df <- read.csv("/Users/emmaoo/Desktop/train.csv")
head(df)
```
# Drop All Uninformative Columns 
```{r}
head(df)
df <- subset(df, select = -c(Patient.Id,Patient.First.Name,Family.Name,Father.s.name,Institute.Name,
                             Location.of.Institute,Place.of.birth,Test.1,Test.2,Test.3,Test.5))
head(df)
dim(df)
```
# Check Missing Values
```{r}
summary(is.na(df))
```

# Check Unique Values  
```{r}
# Check unique values from all columns except Blood.cell.count..mcL. and White.Blood.cell.count..thousand.per.microliter. since we know there's many unique values in those columns

#Extract those columns and save under subdf
subdf <- head(select(df, -Blood.cell.count..mcL.,-White.Blood.cell.count..thousand.per.microliter.,-White.Blood.cell.count..thousand.per.microliter.))

list_unique <- lapply(subdf, unique)# List with unique values
list_unique
```
# Replace "", "_", "Not applicable" values with NA
```{r}
df[df == ""] <- NA
df[df == "-"] <- NA
df[df == "Not applicable"] <- NA
```

```{r}
head(df,2)
```
```{r}
dim(df)
```


```{r}
library(dplyr)
num_df <- select_if(df, is.numeric)  # Subset numeric columns with dplyr
cat_df <- select_if(df,is.character)
head(num_df)
head(cat_df)
```

# Replace Missing Values For Numerical Variables
```{r}
library(dplyr)
library(tidyverse)

df %>% mutate_if(is.numeric, ~ifelse(is.na(.x),median(.x, na.rm = T),.x))
sum(is.na(num_df))
```




```{r}
imputation <- sapply(df, median, na.rm = TRUE)

features <- dim(num_df)[2]
for(ci in 1:features){
  bad_inds <- is.na(df[, ci])
  df[bad_inds, ci] <- imputation[ci]
}
sum(is.na(df))
```






